-- -----------------------------------------------------
-- Schema CPC_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CPC_DB` ;

-- -----------------------------------------------------
-- Schema CPC_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CPC_DB` DEFAULT CHARACTER SET utf8 ;
USE `CPC_DB` ;

-- -----------------------------------------------------
-- Table `CPC_DB`.`PROD_CULT_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`PROD_CULT_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`PROD_CULT_TB` (
  `ID_PROD_CULT` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SENHA_HASH` VARCHAR(60) NOT NULL,
  `ATIVO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID_PROD_CULT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`PROD_PJ_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`PROD_PJ_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`PROD_PJ_TB` (
  `FK_PROD_CULT` VARCHAR(255) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `RAZAO_SOCIAL` VARCHAR(255) NOT NULL,
  `NOME_FANT` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `_UNIQUE` (`CNPJ` ASC) VISIBLE,
  PRIMARY KEY (`FK_PROD_CULT`),
  CONSTRAINT `fk_PROD_PJ_TB_PROD_CULT_TB1`
    FOREIGN KEY (`FK_PROD_CULT`)
    REFERENCES `CPC_DB`.`PROD_CULT_TB` (`ID_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`REPRESENTANTE_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`REPRESENTANTE_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`REPRESENTANTE_TB` (
  `FK_PROD_PJ` VARCHAR(255) NOT NULL,
  `NOME_COMP` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `DATA_NASC` DATE NOT NULL,
  PRIMARY KEY (`FK_PROD_PJ`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_REPRESENTANTE_TB_PROD_PJ_TB1_idx` (`FK_PROD_PJ` ASC) VISIBLE,
  UNIQUE INDEX `FK_PROD_PJ_UNIQUE` (`FK_PROD_PJ` ASC) VISIBLE,
  CONSTRAINT `fk_REPRESENTANTE_TB_PROD_PJ_TB1`
    FOREIGN KEY (`FK_PROD_PJ`)
    REFERENCES `CPC_DB`.`PROD_PJ_TB` (`FK_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`ENDERECO_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`ENDERECO_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`ENDERECO_TB` (
  `FK_PROD_CULT` VARCHAR(255) NOT NULL,
  `LOGRADOURO` VARCHAR(100) NOT NULL,
  `NUMERO` VARCHAR(7) NOT NULL,
  `BAIRRO` VARCHAR(50) NOT NULL,
  `CIDADE` VARCHAR(50) NOT NULL,
  `ESTADO` VARCHAR(20) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`FK_PROD_CULT`),
  CONSTRAINT `fk_ENDERECO_TB_PROD_CULT_TB`
    FOREIGN KEY (`FK_PROD_CULT`)
    REFERENCES `CPC_DB`.`PROD_CULT_TB` (`ID_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`PROD_PF_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`PROD_PF_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`PROD_PF_TB` (
  `FK_PROD_CULT` VARCHAR(255) NOT NULL,
  `NOME_COMP` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `DATA_NASC` DATE NOT NULL,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  PRIMARY KEY (`FK_PROD_CULT`),
  CONSTRAINT `fk_PROD_PF_TB_PROD_CULT_TB1`
    FOREIGN KEY (`FK_PROD_CULT`)
    REFERENCES `CPC_DB`.`PROD_CULT_TB` (`ID_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`CADASTRO_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`CADASTRO_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`CADASTRO_TB` (
  `ID_CAD` INT NOT NULL AUTO_INCREMENT,
  `FK_PROD_CULT` VARCHAR(255) NOT NULL,
  `STATUS_CAD` ENUM('recebido', 'em_analise', 'valido', 'invalido') NOT NULL DEFAULT 'recebido',
  `DATA_CAD` DATE NOT NULL,
  PRIMARY KEY (`ID_CAD`),
  INDEX `fk_CADASTRO_TB_PROD_CULT_TB1_idx` (`FK_PROD_CULT` ASC) VISIBLE,
  CONSTRAINT `fk_CADASTRO_TB_PROD_CULT_TB1`
    FOREIGN KEY (`FK_PROD_CULT`)
    REFERENCES `CPC_DB`.`PROD_CULT_TB` (`ID_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`RENOVACAO_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`RENOVACAO_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`RENOVACAO_TB` (
  `ID_RENOVACAO` INT NOT NULL AUTO_INCREMENT,
  `FK_PROD_CULT` VARCHAR(255) NOT NULL,
  `FK_CAD` INT NOT NULL,
  `STATUS` ENUM('recebido', 'em_analise', 'aprovado', 'negado') NOT NULL DEFAULT 'recebido',
  `DATA_REN` DATE NOT NULL,
  `DATA_EXP` DATE NOT NULL,
  PRIMARY KEY (`ID_RENOVACAO`),
  INDEX `fk_RENOVACAO_TB_CADASTRO_TB1_idx` (`FK_CAD` ASC) VISIBLE,
  INDEX `fk_RENOVACAO_TB_PROD_CULT_TB1_idx` (`FK_PROD_CULT` ASC) VISIBLE,
  CONSTRAINT `fk_RENOVACAO_TB_CADASTRO_TB1`
    FOREIGN KEY (`FK_CAD`)
    REFERENCES `CPC_DB`.`CADASTRO_TB` (`ID_CAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RENOVACAO_TB_PROD_CULT_TB1`
    FOREIGN KEY (`FK_PROD_CULT`)
    REFERENCES `CPC_DB`.`PROD_CULT_TB` (`ID_PROD_CULT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`ANEXO_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`ANEXO_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`ANEXO_TB` (
  `ID_ANEXO` INT NOT NULL AUTO_INCREMENT,
  `FK_CAD` INT NULL,
  `FK_REN` INT NULL,
  `NOME_ANEXO` ENUM('Curriculo', 'Contrato_Social', 'Comprovante_de_Endereco', 'Cartao_CNPJ', 'RG_CNH_Carteira_Trabalho', 'Certidao_Regularidade_Fiscal', 'Certidao_Prestacao_Contas') NOT NULL,
  `DATA_UPLOAD` DATE NOT NULL,
  `EXTENSAO` VARCHAR(6) NOT NULL,
  `STATUS` ENUM('recebido', 'em_analise', 'valido', 'invalido') NOT NULL DEFAULT 'recebido',
  `ARQUIVO` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`ID_ANEXO`),
  INDEX `fk_ANEXO_TB_CADASTRO_TB1_idx` (`FK_CAD` ASC) VISIBLE,
  INDEX `fk_ANEXO_TB_RENOVACAO_TB1_idx` (`FK_REN` ASC) VISIBLE,
  CONSTRAINT `fk_ANEXO_TB_CADASTRO_TB1`
    FOREIGN KEY (`FK_CAD`)
    REFERENCES `CPC_DB`.`CADASTRO_TB` (`ID_CAD`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ANEXO_TB_RENOVACAO_TB1`
    FOREIGN KEY (`FK_REN`)
    REFERENCES `CPC_DB`.`RENOVACAO_TB` (`ID_RENOVACAO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPC_DB`.`FUNCIONARIO_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPC_DB`.`FUNCIONARIO_TB` ;

CREATE TABLE IF NOT EXISTS `CPC_DB`.`FUNCIONARIO_TB` (
  `COD_FUNC` INT NOT NULL AUTO_INCREMENT,
  `NOME_COMP` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(90) NOT NULL,
  `SENHA_HASH` VARCHAR(60) NOT NULL,
  `ATIVO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`COD_FUNC`))
ENGINE = InnoDB;


DROP USER IF EXISTS User_Prod;
CREATE USER 'User_Prod' IDENTIFIED BY '123456';

GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`PROD_CULT_TB` TO 'User_Prod';
GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`PROD_PJ_TB` TO 'User_Prod';
GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`REPRESENTANTE_TB` TO 'User_Prod';
GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`ENDERECO_TB` TO 'User_Prod';
GRANT SELECT, INSERT, UPDATE ON TABLE `CPC_DB`.`PROD_PF_TB` TO 'User_Prod';
GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`ANEXO_TB` TO 'User_Prod';
GRANT INSERT, SELECT, UPDATE ON TABLE `CPC_DB`.`CADASTRO_TB` TO 'User_Prod';
GRANT INSERT, UPDATE, SELECT ON TABLE `CPC_DB`.`RENOVACAO_TB` TO 'User_Prod';
DROP USER IF EXISTS User_Func;

CREATE USER 'User_Func' IDENTIFIED BY '123456';

GRANT ALL ON TABLE `CPC_DB`.`PROD_CULT_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`PROD_PJ_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`REPRESENTANTE_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`ENDERECO_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`PROD_PF_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`ANEXO_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`FUNCIONARIO_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`CADASTRO_TB` TO 'User_Func';
GRANT ALL ON TABLE `CPC_DB`.`RENOVACAO_TB` TO 'User_Func';
GRANT ALL ON `CPC_DB`.* TO 'User_Func';

